require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'sorbet/**/*'
    - 'tmp/**/*'
    - 'pkg/**/*'
    - 'coverage/**/*'
    - 'doc/**/*'
    - 'node_modules/**/*'
    - '*.gemspec'

# Disable documentation requirement for now
Style/Documentation:
  Enabled: false

# Allow longer blocks in specs and rake tasks
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'
    - '**/*.rake'
    - 'config/**/*'

# Allow longer lines for readability
Layout/LineLength:
  Max: 120
  IgnoredPatterns:
    - '\A\s*#'  # Comments
    - '\A\s*it\s'  # RSpec examples
    - '\A\s*describe\s'  # RSpec describe blocks
    - '\A\s*context\s'  # RSpec context blocks

# Allow longer methods in specs
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'
  Max: 15

# Allow longer classes
Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

# Allow more parameters for configuration objects
Metrics/ParameterLists:
  Max: 6

# Allow complex methods in specs
Metrics/CyclomaticComplexity:
  Exclude:
    - 'spec/**/*'

# Performance optimizations
Performance/StringReplacement:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/StringInclude:
  Enabled: true

# RSpec specific configurations
RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'
    - 'spec/performance/**/*'

# Sorbet specific configurations
Sorbet/FalseSigil:
  Enabled: true

Sorbet/ValidSigil:
  Enabled: true

Sorbet/TrueSigil:
  Enabled: false  # Allow gradual typing

# Style preferences
Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

# Layout preferences
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# Allow compact style for simple hashes
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

# Naming conventions
Naming/VariableNumber:
  EnforcedStyle: snake_case

Naming/AccessorMethodName:
  Enabled: false  # Allow get_* and set_* methods

# Threading and concurrency
Style/GlobalStdStream:
  Enabled: false  # Allow STDOUT/STDERR usage

# Disable some restrictive cops
Style/NumericPredicate:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

# Allow both and/or and &&/||
Style/AndOr:
  Enabled: false

# Allow non-ASCII characters in comments
Style/AsciiComments:
  Enabled: false

# Custom cops for Cassandra-CPP
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# Security
Security/YAMLLoad:
  Enabled: true

Security/MarshalLoad:
  Enabled: true

Security/Eval:
  Enabled: true