name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RUBY_VERSION: 3.4.1
  CASSANDRA_VERSION: 4.1

jobs:
  # Lint checks
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config \
            libuv1-dev libssl-dev zlib1g-dev

      - name: Run RuboCop
        run: bundle exec rubocop --parallel --format github

      - name: Run Sorbet type checking
        run: bundle exec srb tc

  # Test suite
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      cassandra:
        image: cassandra:4.1
        env:
          CASSANDRA_CLUSTER_NAME: TestCluster
          CASSANDRA_NUM_TOKENS: 256
          CASSANDRA_RPC_ADDRESS: 0.0.0.0
          CASSANDRA_LISTEN_ADDRESS: cassandra
          CASSANDRA_BROADCAST_ADDRESS: 127.0.0.1
          CASSANDRA_BROADCAST_RPC_ADDRESS: 127.0.0.1
          MAX_HEAP_SIZE: 512m
          HEAP_NEWSIZE: 100m
        ports:
          - 9042:9042
        options: >-
          --health-cmd "cqlsh -e 'describe keyspaces'"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 10
          --health-start-period 60s

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config \
            libuv1-dev libssl-dev zlib1g-dev libgmp-dev libffi-dev \
            libyaml-dev libreadline-dev libncurses5-dev

      - name: Install DataStax C++ driver
        run: |
          cd /tmp
          wget https://github.com/datastax/cpp-driver/archive/2.16.2.tar.gz
          tar -xzf 2.16.2.tar.gz
          cd cpp-driver-2.16.2
          mkdir build && cd build
          cmake .. -DCASS_BUILD_STATIC=ON -DCASS_BUILD_SHARED=ON \
            -DCASS_USE_STATIC_LIBS=ON -DCASS_USE_ZLIB=ON -DCASS_USE_OPENSSL=ON
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      - name: Wait for Cassandra
        run: |
          timeout 300 bash -c 'until nc -z localhost 9042; do sleep 1; done'
          sleep 10

      - name: Set up test keyspace
        run: |
          cqlsh -e "CREATE KEYSPACE IF NOT EXISTS cassandra_cpp_test
                    WITH REPLICATION = {
                      'class': 'SimpleStrategy',
                      'replication_factor': 1
                    };"

      - name: Run tests
        run: bundle exec rspec --format documentation --format RspecJunitFormatter --out tmp/rspec.xml
        env:
          CASSANDRA_HOSTS: localhost
          CASSANDRA_PORT: 9042
          CASSANDRA_KEYSPACE: cassandra_cpp_test
          COVERAGE: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: tmp/rspec.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: test-coverage